name: CI
on:
  - push
  - pull_request
jobs:
  haskell:
    name: stack build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '9.8.4'
          enable-stack: true
      - run: sudo apt-get install wamerican-small
      - uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('anagrep.cabal') }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - run: stack build --system-ghc --test --bench
